<?php
/**
 * @file
 * Code for the Page Content Type feature.
 */

include_once 'page_content_type.features.inc';

/**
 * Implements hook_form_FORM_ID_alter();
 */
function page_content_type_form_page_node_form_alter($form, $form_state) {
  drupal_add_js(drupal_get_path('module', 'page_content_type') . '/js/page_content_type.js');
}

/**
 * Implements hook_node_update().
 * 
 * Case 50686.
 */
function page_content_type_node_update($node) {
  // Check if same redirect exists as alias and remove it to avoid infinite loop.
  if ($redirect = redirect_load_by_source($node->path['alias'])) {
    redirect_delete($redirect->rid);
  }
}
