<?php
/**
 * @file
 * Code for the Google Analytics for Dashboard feature.
 */

include_once 'dashboardga.features.inc';

/**
 * Implements hook_menu().
 */
function dashboardga_menu() {
  $items['admin/dashboard/reports'] = array(
    'title' => 'Reports', 
    'description' => 'DLAW Dashboard - Report',
    'page callback' => 'dashboardga_report_page', 
    'access callback' => 'dashboardga_report_access',
    'weight' => 15,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 *
 */
function dashboardga_report_access() {
  if ('UA-0000000-00' == variable_get('googleanalytics_account', 'UA-0000000-00')) {
    return FALSE;
  }

  return user_access('access dlaw dashboard');
}

/**
 * Implements hook_theme_registry_alter().
 */
function dashboardga_theme_registry_alter(&$theme_registry) {
  $theme_registry['file_link']['theme_path'] = drupal_get_path('module', 'dashboardga');
  $theme_registry['file_link']['function'] = 'dashboardga_file_link';
}

/**
 * Override core's theme_file_link.
 * To insert onclick attr for Google Analytics download track.
 */
function dashboardga_file_link($variables) {
  $file = $variables['file'];
  $icon_directory = $variables['icon_directory'];

  $url = file_create_url($file->uri);
  $icon = theme('file_icon', array('file' => $file, 'icon_directory' => $icon_directory));

  // Set options as per anchor format described at
  // http://microformats.org/wiki/file-format-examples
  $options = array(
    'attributes' => array(
      'type' => $file->filemime . '; length=' . $file->filesize,
    ),
  );

  // Use the description as the link text if available.
  if (empty($file->description)) {
    $link_text = $file->filename;
  }
  else {
    $link_text = $file->description;
    $options['attributes']['title'] = check_plain($file->filename);
  }

  $nid  = 'nid:' . (is_numeric(1) ? arg(1) : '');
  $file = 'fid:' . $file->fid . ': ' . htmlentities($file->filename);
  $options['attributes']['onclick'] = "_gaq.push(['_trackEvent', 'Download', '$nid', '$file']);";

  return '<span class="file">' . $icon . ' ' . l($link_text, $url, $options) . '</span>';
}

/**
 *  Implements hook_block_info().
 */
function dashboardga_block_info() {
  $blocks['ga'] = array(
    'info' => t('Google Analytics'),
  );

  return $blocks;
}

/**
 *  Implements hook_block_view().
 */
function dashboardga_block_view($delta = '') {
  $block = array();

  if ($delta == 'ga') {
    if ('UA-0000000-00' == variable_get('googleanalytics_account', 'UA-0000000-00')) {
      // Add blanks. Otherwise, the block would appear with annoying "(empty)"
      $block['subject'] = ' ';
      $block['content'] = ' ';
      
      return $block;
    }

    drupal_add_css(drupal_get_path('module', 'dashboardga') . '/css/dashboardga.css');

    $output = '';


    


    

    // Pull GA data. *********************************************************
    $params = array(
      'metrics' => array('ga:pageviews'),
      'dimensions' => array('ga:date'),
      'segment' => 'gaid::-1',
      'sort_metric' => array('ga:date'),
      'start_date' => strtotime('-30 days'),
      'end_date' => strtotime('-1 day'),
    );
    $feed = google_analytics_api_report_data($params);

    $data = array();
    foreach ($feed->results->rows as $row) {
      $data[] = array(date('j', strtotime($row['date'])), (int)$row['pageviews']);
    }

    if (empty($feed->error)) {
      $chart = array(
        '#type' => 'chart',
        '#chart_type' => 'area',
        '#legend_position' => 'none',
      );

      $chart['visitors'] = array(
        '#type' => 'chart_data',
        '#title' => t('Page Views'),
        '#data' => $data,
        '#color' => '#4DB8DB',
      );
    }
    else {
      $chart = array('#markup' => '<p style="margin:2em 4em 4em">Google Analytics Report not set up.</p>');
    }

    $output .= '<h2 class="ga_list_title last_30"><i class="fa fa-bar-chart-o"></i> Page Views in the last 30 days</h2>' . drupal_render($chart);


    // Pull GA data. *********************************************************
    // Get last 30 days.
    $params = array(
      'metrics' => array('ga:sessions', 'ga:users', 'ga:pageviews'),
      'start_date' => strtotime('-30 days'),
      'end_date' => strtotime('-1 day'),
    );
    $feed = google_analytics_api_report_data($params);
    
    $result = $feed->results->rows[0];

    // Get 30 days before past 30 days for comparison.
    $params = array(
      'metrics' => array('ga:sessions', 'ga:users', 'ga:pageviews'),
      'start_date' => strtotime('-60 days'),
      'end_date' => strtotime('-31 day'),
    );
    $feed = google_analytics_api_report_data($params);
    
    $result_prev = $feed->results->rows[0];

    $change = round(($result['sessions'] - $result_prev['sessions'])/$result_prev['sessions']*100, 1);
    $change = ($change >= 0 ? '+' : '') . $change;
    $change_class = $change >= 0 ? 'ga-change-up' : 'ga-change-down';
    $list[] = '<div class="change_container"> <div class="ga-label">Visits <br/></div>                
                <div class="clearfix cgange_holder">
                  <span class="ga-value">' 
                    . number_format($result['sessions']) . 
                    '</span>
                <span class="ga-percent ' . $change_class . '">'
                . $change . 
                '%</span>
                </div></div>';

    $change = round(($result['users'] - $result_prev['users'])/$result_prev['users']*100, 1);
    $change = ($change >= 0 ? '+' : '') . $change;
    $change_class = $change >= 0 ? 'ga-change-up' : 'ga-change-down';

    $list[] = '<div class="change_container"> <div class="ga-label">Unique Visitors <br/></div>                
                <div class="clearfix cgange_holder">
                  <span class="ga-value">' 
                    . number_format($result['users']) .
                  '</span> 
                <span class="ga-percent ' . $change_class . '">'
                  . $change . 
                '%</span>
                </div></div>';

    $page_visit = $result['pageviews'] / $result['sessions'];
    $page_visit_prev = $result_prev['pageviews'] / $result_prev['sessions'];
    $change = round(($page_visit - $page_visit_prev)/$page_visit_prev*100, 1);
    $change = ($change >= 0 ? '+' : '') . $change;
    $change_class = $change >= 0 ? 'ga-change-up' : 'ga-change-down';

    $list[] = '<div class="change_container"> <div class="ga-label">Pages/Visit <br/></div>                 
                <div class="clearfix cgange_holder">
                  <span class="ga-value">' 
                    . round($page_visit, 1) . 
                  '</span> 
                <span class="ga-percent ' . $change_class . '">'
                . $change .
                '%</span>
                </div></div>';

    // TODO: $list[] = FEEDBACKS

    $attributes = array('class' => array('ga_site_usage_list', 'clearfix'));
    $output .= '<h2 class="ga_list_title last_seven"><i class="fa fa-tachometer"></i> Site Usage (last 30 days)</h2>' . theme('item_list', array('items' => $list, 'attributes' => $attributes ));


    // Pull GA data. *********************************************************
    $params = array(
      'metrics' => array('ga:pageviews'),
      'dimensions' => array('ga:pagePath', 'ga:pageTitle'),
      'segment' => 'gaid::-1',
      'sort_metric' => array('-ga:pageviews'),
      'start_date' => strtotime('-30 days'),
      'end_date' => strtotime('-1 day'),
      'sort' => '-ga:pageviews',
      'filters' => 'ga:pageTitle!=(not set)',
      'max_results' => 10,
    );
    $feed = google_analytics_api_report_data($params);
    
    $list = array();
    foreach ($feed->results->rows as $row) {
      if ($row['pagePath'] == '/') {
        $title = 'Home page';
      }
      else {
        list($title, ) = explode(' | ', $row['pageTitle']);
      }
      $list[] = '<span class="ga-link">' . l($title, substr($row['pagePath'], 1)) . '</span>' . '<span class="ga-num">' . number_format($row['pageviews']) . '</span>';
    }

    $attributes = array('class' => array('ga_list','ga_most_visited_list','clearfix'));
    $output .= '<h2 class="ga_list_title most_visited" ><i class="fa fa-desktop"></i>Most Visited Pages (Popular Pages)</h2>' . theme('item_list', array('items' => $list, 'type' => 'ul', 'attributes' => $attributes) );
    

    // Pull GA data. *********************************************************
    $params = array(
      'metrics' => array('ga:sessions'),
      'dimensions' => array('ga:source', 'ga:medium'),
      'sort_metric' => array('-ga:sessions'),
      'filters' => 'ga:medium==referral',
      'start_date' => strtotime('-30 days'),
      'end_date' => strtotime('-1 day'),
      'max_results' => 10,
    );

    $feed = google_analytics_api_report_data($params);
    
    $list = array();
    foreach ($feed->results->rows as $row) {
      $list[] = '<span class="ga-link">' . $row['source'] . '</span>' . '<span class="ga-num">' . number_format($row['sessions']) . '</span>';
    }
    $attributes = array('class' => array('ga_list','ga_referred_trafic','clearfix'));
    $output .= '<h2 class="ga_list_title" ><i class="fa fa-truck"></i> Referral Traffic Sources</h2>' . theme('item_list', array('items' => $list, 'type' => 'ul', 'attributes' => $attributes) );


    // Pull GA data. *********************************************************
    $params = array(
      'metrics' => array('ga:sessions'),
      'dimensions' => array('ga:keyword'),
      'sort_metric' => array('-ga:sessions'),
      'start_date' => strtotime('-30 days'),
      'end_date' => strtotime('-1 day'),
      'filters' => 'ga:keyword!=(not provided);ga:keyword!=(not set)',
      'max_results' => 10,
    );

    $feed = google_analytics_api_report_data($params);
    
    $list = array();
    foreach ($feed->results->rows as $row) {
      $list[] = '<span class="ga-link">' . $row['keyword'] . '</span>' . '<span class="ga-num">' . number_format($row['sessions']) . '</span>';
    }

    $attributes = array('class' => array('ga_list','ga_google_searches','clearfix'));
    $output .= '<h2 class="ga_list_title"><i class="fa fa-globe"></i> Google Searches</h2>' . theme('item_list', array('items' => $list, 'type' => 'ul', 'attributes' => $attributes) );


    // Pull GA data. *********************************************************
    /*
    Case 42104: Comment out until figuring out to work with GA for site search.
    $params = array(
      'metrics' => array('ga:sessions'),
      'dimensions' => array('ga:searchKeyword'),
      'sort_metric' => array('-ga:sessions'),
      'start_date' => strtotime('-30 days'),
      'end_date' => strtotime('-1 day'),
      // 'filters' => 'ga:keyword!=(not provided);ga:keyword!=(not set)',
      'max_results' => 10,
    );

    $feed = google_analytics_api_report_data($params);
    
    $list = array();
    foreach ($feed->results->rows as $row) {
      $list[] = '<span class="ga-link">' . $row['searchkeyword'] . '</span>' . '<span class="ga-num">' . number_format($row['sessions']) . '</span>';
    }

    $attributes = array('class' => array('ga_list','ga_site_searches','clearfix'));
    $output .= '<h2 class="ga_list_title"><i class="fa fa-search"></i> Site Searches</h2>' . theme('item_list', array('items' => $list, 'type' => 'ul', 'attributes' => $attributes) );
    */

    $block['content'] = $output;
    $block['subject'] = '<span class="google_analytics_title">Google Analytics</span>';
  }

  return $block;
}

/**
 *  Menu callback for admin/dashboard/report.
 */
function dashboardga_report_page() {
  if ('UA-0000000-00' == variable_get('googleanalytics_account', 'UA-0000000-00')) {
    return 'Google Analytics not configured yet.';
  }

  $start_time = strtotime('1/1 last year');
  $end_time   = strtotime('1/1 this year');
  $last_year  = date('Y', strtotime('last year'));
  $prev_year  = date('Y', strtotime('-2 years'));
  drupal_add_css(drupal_get_path('module', 'dashboardga') . '/css/dashboardga.css');

  $output = '';

  // Pull GA data. *********************************************************
  $params = array(
    'metrics' => array('ga:sessions', 'ga:users', 'ga:pageviews'),
    'start_date' => $start_time,
    'end_date' => $end_time,
  );
  $feed = google_analytics_api_report_data($params);
  
  $result = $feed->results->rows[0];

  // Get 1 year before last year.
  $params = array(
    'metrics' => array('ga:sessions', 'ga:users', 'ga:pageviews'),
    'start_date' => strtotime('1/1 -2 years'),
    'end_date' => strtotime('1/1 -1 year'),
  );
  $feed = google_analytics_api_report_data($params);
  
  $result_prev = $feed->results->rows[0];

  $rows = array();

  $change = round(($result['pageviews'] - $result_prev['pageviews'])/$result_prev['pageviews']*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $rows[] = array(
      'Page views',
      number_format($result_prev['pageviews']),
      number_format($result['pageviews']),
      $change . '%',
  );

  $change = round(($result['sessions'] - $result_prev['sessions'])/$result_prev['sessions']*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $rows[] = array(
      'Sessions',
      number_format($result_prev['sessions']),
      number_format($result['sessions']),
      $change . '%',
  );

  $change = round(($result['users'] - $result_prev['users'])/$result_prev['users']*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $rows[] = array(
      'Unique visitors',
      number_format($result_prev['users']),
      number_format($result['users']),
      $change . '%',
  );

  $pps_prev = $result_prev['pageviews'] / $result_prev['sessions'];
  $pps = $result['pageviews'] / $result['sessions'];
  $change = round(($pps - $pps_prev)/$pps_prev*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $rows[] = array(
      'Pages per session',
      number_format($result_prev['pageviews'] / $result_prev['sessions'], 2),
      number_format($result['pageviews'] / $result['sessions'], 2),
      $change . '%',
  );

  $header = array('Metric', $prev_year, $last_year, 'Change');

  $output .= '<h2 class="ga_list_title"><i class="fa fa-tachometer"></i> Site Usage</h2>'
           . theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('class' => array('ga_list'))));

  // Pull GA data. *********************************************************
  $params = array(
    'metrics' => array('ga:sessions'),
    'dimensions' => array('ga:deviceCategory'),
    'start_date' => $start_time,
    'end_date' => $end_time,
  );
  $feed = google_analytics_api_report_data($params);

  $result = array('total' => 0);
  foreach ($feed->results->rows as $res) {
    $result[$res['deviceCategory']] = $res['sessions'];
    $result['total'] += $res['sessions'];
  }

  // Get 1 year before last year.
  $params = array(
    'metrics' => array('ga:sessions'),
    'dimensions' => array('ga:deviceCategory'),
    'start_date' => strtotime('1/1 -2 years'),
    'end_date' => strtotime('1/1 -1 year'),
  );
  $feed = google_analytics_api_report_data($params);

  $result_prev = array('total' => 0);
  foreach ($feed->results->rows as $res) {
    $result_prev[$res['deviceCategory']] = $res['sessions'];
    $result_prev['total'] += $res['sessions'];
  }

  $rows = array();

  $percent_prev = $result_prev['desktop'] / $result_prev['total'] * 100;
  $percent = $result['desktop'] / $result['total'] * 100;
  $change = round(($percent - $percent_prev)/$percent_prev*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $rows[] = array(
      'Device: Desktop',
      round($percent_prev, 1) . '%',
      round($percent, 1) . '%',
      $change . '%',
  );

  $percent_prev = $result_prev['mobile'] / $result_prev['total'] * 100;
  $percent = $result['mobile'] / $result['total'] * 100;
  $change = round(($percent - $percent_prev)/$percent_prev*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $rows[] = array(
      'Device: Mobile',
      round($percent_prev, 1) . '%',
      round($percent, 1) . '%',
      $change . '%',
  );

  $percent_prev = $result_prev['tablet'] / $result_prev['total'] * 100;
  $percent = $result['tablet'] / $result['total'] * 100;
  $change = round(($percent - $percent_prev)/$percent_prev*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $rows[] = array(
      'Device: Tablet',
      round($percent_prev, 1) . '%',
      round($percent, 1) . '%',
      $change . '%',
  );

  $header = array('Metric', $prev_year, $last_year, 'Change');

  $output .= '<h2 class="ga_list_title"><i class="fa fa-mobile"></i> Devices</h2>'
           . theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('class' => array('ga_list'))));

  // Pull GA data. *********************************************************
  $params = array(
    'metrics' => array('ga:pageviews'),
    'dimensions' => array('ga:month'),
    'segment' => 'gaid::-1',
    'sort_metric' => array('ga:month'),
    'start_date' => $start_time,
    'end_date' => $end_time,
  );
  $feed = google_analytics_api_report_data($params);

  $data1 = $data2 = array('01' => 0, '02' => 0, '03' => 0, '04' => 0, '05' => 0, '06' => 0,
                          '07' => 0, '08' => 0, '09' => 0, '10' => 0, '11' => 0, '12' => 0);
  foreach ($feed->results->rows as $row) {
    $data1[$row['month']] = (int)$row['pageviews'];
  }

  // Get 1 year before last year.
  $params = array(
    'metrics' => array('ga:pageviews'),
    'dimensions' => array('ga:month'),
    'segment' => 'gaid::-1',
    'sort_metric' => array('ga:month'),
    'start_date' => strtotime('1/1 -2 years'),
    'end_date' => strtotime('1/1 -1 year'),
  );
  $feed = google_analytics_api_report_data($params);

  foreach ($feed->results->rows as $row) {
    $data2[$row['month']] = (int)$row['pageviews'];
  }

  $chart = array(
    '#type' => 'chart',
    '#chart_type' => 'line',
    '#legend_position' => 'bottom',
  );

  $chart['prev_year'] = array(
    '#type' => 'chart_data',
    '#title' => 'Year ' . $prev_year,
    '#data' => array_values($data2),
    '#color' => '#09F',
  );

  $chart['last_year'] = array(
    '#type' => 'chart_data',
    '#title' => 'Year ' . $last_year,
    '#data' => array_values($data1),
    '#color' => '#F60',
  );

  $chart['xaxis'] = array(
    '#type' => 'chart_xaxis',
    '#labels' => array('01','02','03','04','05','06','07','08','09','10','11','12'),
  );

  $output .= '<h2 class="ga_list_title last_30"><i class="fa fa-bar-chart-o"></i> Page Views in ' . $last_year . '</h2>' . drupal_render($chart);

  // Pull GA data. *********************************************************
  /*$params = array(
    'metrics' => array('ga:sessions', 'ga:users', 'ga:pageviews'),
    'start_date' => $start_time,
    'end_date' => $end_time,
  );
  $feed = google_analytics_api_report_data($params);
  
  $result = $feed->results->rows[0];

  // Get 1 year before last year.
  $params = array(
    'metrics' => array('ga:sessions', 'ga:users', 'ga:pageviews'),
    'start_date' => strtotime('1/1 -2 years'),
    'end_date' => strtotime('1/1 -1 year'),
  );
  $feed = google_analytics_api_report_data($params);
  
  $result_prev = $feed->results->rows[0];

  $change = round(($result['sessions'] - $result_prev['sessions'])/$result_prev['sessions']*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $change_class = $change >= 0 ? 'ga-change-up' : 'ga-change-down';
  $list[] = '<div class="change_container"> <div class="ga-label">Visits <br/></div>                
              <div class="clearfix cgange_holder">
                <span class="ga-value">' 
                  . number_format($result['sessions']) . 
                  '</span>
              <span class="ga-percent ' . $change_class . '">'
              . $change . 
              '%</span>
              </div></div>';

  $change = round(($result['users'] - $result_prev['users'])/$result_prev['users']*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $change_class = $change >= 0 ? 'ga-change-up' : 'ga-change-down';

  $list[] = '<div class="change_container"> <div class="ga-label">Unique Visitors <br/></div>                
              <div class="clearfix cgange_holder">
                <span class="ga-value">' 
                  . number_format($result['users']) .
                '</span> 
              <span class="ga-percent ' . $change_class . '">'
                . $change . 
              '%</span>
              </div></div>';

  $page_visit = round(($result['pageviews'] / $result['sessions']), 2);
  $page_visit_prev = round(($result_prev['pageviews'] / $result_prev['sessions']), 2);
  $change = round(($page_visit - $page_visit_prev)/$page_visit_prev*100, 1);
  $change = ($change >= 0 ? '+' : '') . $change;
  $change_class = $change >= 0 ? 'ga-change-up' : 'ga-change-down';

  $list[] = '<div class="change_container"> <div class="ga-label">Pages/Visit <br/></div>                 
              <div class="clearfix cgange_holder">
                <span class="ga-value">' 
                  . round($page_visit, 1) . 
                '</span> 
              <span class="ga-percent ' . $change_class . '">'
              . $change .
              '%</span>
              </div></div>';

  $attributes = array('class' => array('ga_site_usage_list', 'clearfix'));
  $output .= '<h2 class="ga_list_title last_seven"><i class="fa fa-tachometer"></i> Site Usage in ' . $last_year . ' (with changes compared to the previous year)</h2>' . theme('item_list', array('items' => $list, 'attributes' => $attributes ));*/


  // Pull GA data. *********************************************************
  $params = array(
    'metrics' => array('ga:pageviews'),
    'dimensions' => array('ga:pagePath', 'ga:pageTitle'),
    'segment' => 'gaid::-1',
    'sort_metric' => array('-ga:pageviews'),
    'start_date' => $start_time,
    'end_date' => $end_time,
    'sort' => '-ga:pageviews',
    'filters' => 'ga:pageTitle!=(not set)',
    'max_results' => 100,
  );
  $feed = google_analytics_api_report_data($params);
  
  $list = $counts = $titles = array();
  foreach ($feed->results->rows as $row) {
    if ($row['pagePath'] == '/') {
      $title = 'Home page';
    }
    else {
      list($title, ) = explode(' | ', $row['pageTitle']);
    }

    if (isset($counts[$row['pagePath']])) {
      $counts[$row['pagePath']] += $row['pageviews'];
    }
    else {
      $counts[$row['pagePath']] = $row['pageviews'];
      $titles[$row['pagePath']] = $title;
    }
  }

  arsort($counts);
  $counts = array_slice($counts, 0, 25);
  
  foreach ($counts as $path => $views) {
    $list[] = '<span class="ga-link">' . l($titles[$path], substr($path, 1)) . '</span>' . '<span class="ga-num">' . number_format($views) . '</span>';
  }

  $attributes = array('class' => array('ga_list','ga_most_visited_list','clearfix'));
  $output .= '<h2 class="ga_list_title most_visited" ><i class="fa fa-desktop"></i>Most Visited Pages (Popular Pages) in ' . $last_year . '</h2>' . theme('item_list', array('items' => $list, 'type' => 'ul', 'attributes' => $attributes) );
  

  // Pull GA data. *********************************************************
  $params = array(
    'metrics' => array('ga:sessions'),
    'dimensions' => array('ga:source', 'ga:medium'),
    'sort_metric' => array('-ga:sessions'),
    'filters' => 'ga:medium==referral',
    'start_date' => $start_time,
    'end_date' => $end_time,
    'max_results' => 25,
  );

  $feed = google_analytics_api_report_data($params);
  
  $list = array();
  foreach ($feed->results->rows as $row) {
    $list[] = '<span class="ga-link">' . $row['source'] . '</span>' . '<span class="ga-num">' . number_format($row['sessions']) . '</span>';
  }
  $attributes = array('class' => array('ga_list','ga_referred_trafic','clearfix'));
  $output .= '<h2 class="ga_list_title" ><i class="fa fa-truck"></i> Referral Traffic Sources in ' . $last_year . '</h2>' . theme('item_list', array('items' => $list, 'type' => 'ul', 'attributes' => $attributes) );


  // Pull GA data. *********************************************************
  $params = array(
    'metrics' => array('ga:sessions'),
    'dimensions' => array('ga:keyword'),
    'sort_metric' => array('-ga:sessions'),
    'start_date' => $start_time,
    'end_date' => $end_time,
    'filters' => 'ga:keyword!=(not provided);ga:keyword!=(not set)',
    'max_results' => 25,
  );

  $feed = google_analytics_api_report_data($params);
  
  $list = array();
  foreach ($feed->results->rows as $row) {
    $list[] = '<span class="ga-link">' . $row['keyword'] . '</span>' . '<span class="ga-num">' . number_format($row['sessions']) . '</span>';
  }

  $attributes = array('class' => array('ga_list','ga_google_searches','clearfix'));
  $output .= '<h2 class="ga_list_title"><i class="fa fa-globe"></i> Google Searches in ' . $last_year . '</h2>' . theme('item_list', array('items' => $list, 'type' => 'ul', 'attributes' => $attributes) );

  // Reuse styles defined for dashboard block.
  return '<div id="dashboard"><div class="block block-dashboardga">' . $output . '</div></div>';
}
